# Generated by Django 5.1.7 on 2025-03-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttransaction',
            name='encrypted_timestamp',
        ),
    ]
