# Generated by Django 5.1.7 on 2025-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_investmenttransaction_encrypted_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='encrypted_timestamp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
